### ISSUE TITLE
Tests hang on the CI

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/MusicStore#654] opened 2016-05-02 18:36 UTC
On Win 2008, there was a process running after the tests completed. Subsequent runs failed to start because `git clean` failed.

All I could get is that the command line for that process is:
`"D:\df3ce1ac-22fd-4b89-a5ad-25c606034f91\MusicStore.exe"  --server.urls http://localhost:5014/  --server Microsoft.AspNetCore.Server.Kestrel`

The build script should kill any running music store and/or dotnet. If that's to complicated to do, restarting the agent after each run might be a reasonable solution, especially for the long running test runs.

cc @kichalla

**Comment by BrennanConroy** [comment] 2016-05-02 18:38
Shouldn't we figure out the root cause of why it was still running?

**Comment by victorhurdugaci** [comment] 2016-05-02 18:39
We should but there's a chance that we cannot handle all cases (ex: the test runner crashes).

Here's a link about restarting the agent: https://youtrack.jetbrains.com/issue/TW-36298

**Comment by Eilon** [comment] 2017-04-19 21:26
Super old, so closing this.

**Closed by Eilon** 2017-04-19 21:26 UTC
