### ISSUE TITLE
Start project

### ISSUE THREAD

**Issue by QuanHuynhM** [aspnet/MusicStore#791] opened 2017-05-11 12:40 UTC
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		One or more packages are incompatible with .NETCoreApp,Version=v1.0.				
Error		Package Microsoft.Extensions.SecretManager.Tools 2.0.0-preview2-24979 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Extensions.SecretManager.Tools 2.0.0-preview2-24979 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)		
Error		Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0 (linux-x64)'.				
Error		Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0 (osx-x64)'.		
Error		Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0 (win7-x64)'.	
Error		Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0 (win7-x86)'.	
Error		Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0'.
Error		Unexpected dependency 'Microsoft.NETCore.App' with no version number.	MusicStore	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
```

**Comment by Eilon** [comment] 2017-05-11 21:20
@natemcmaster @kichalla - any ideas on this?

**Comment by natemcmaster** [comment] 2017-05-11 21:23
@QuanHuynhM what version of Visual Studio are you using?

**Comment by QuanHuynhM** [comment] 2017-05-11 23:05
@natemcmaster I use visual studio 2017! :). And i see packages is incompetible

**Comment by Eilon** [comment] 2017-05-11 23:18
You might need to get VS2017 Update 3 Preview 1, which was just released: https://www.visualstudio.com/vs/preview/?utm_source=VSIDE-15-3&utm_medium=blogpost&utm_campaign=build2017

**Comment by QuanHuynhM** [comment] 2017-05-12 03:37
Now I use version 15.2(26430.4) Release. But VS 2017 doesn't notification for me to update @Eilon

**Comment by Eilon** [comment] 2017-05-12 16:45
@QuanHuynhM this is a preview release, so I'm not sure if you'll get an automatic notification for it. You'll need to download it manually.

**Comment by Eilon** [comment] 2017-06-06 17:26
Closing because there is not enough information to reproduce this problem.

**Closed by Eilon** 2017-06-06 17:26 UTC
